server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/jvaldiviab/bootcamp_config-data
          search-paths: /
  application:
    name: config-server


